const rockButton = document.getElementById('rock')
const paperButton = document.getElementById('paper')
const scissorsButton = document.getElementById('scissors')
const results = document.querySelector('.result') 
const compImg = document.querySelector('.comp-img') 
const userImg = document.querySelector('.user-img') 